name: buxing
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  uuid: ^3.0.5
  convert: ^3.0.1
  mgenware_dart_lints: ^1.0.0
dependencies:
  http: ^0.13.4
