name: buxing
description: An HTTP file downloader packed with many features -> resumable downloads, multiple connections, buffering, auto-retry, etc.
version: 0.1.2
homepage: https://github.com/mgenware/buxing

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0
  uuid: ^3.0.5
  convert: ^3.0.1
  mgenware_dart_lints: ^1.0.0
  path: ^1.8.0
  crypto: ^3.0.1
dependencies:
  http: ^0.13.4
  meta: ^1.7.0
  async: ^2.8.2
  ansicolor: ^2.0.1
  buffered_list_stream: ^1.0.0
